#!/bin/bash

source ~/.openrc
source config

function glance_flags() {
	case $1 in
		"image-create")
			if [ "$VIRT" == "kvm" ] ; then
				echo ""
			elif [ "$VIRT" == "xen-hvm" ] ; then
				echo "--property vm_mode=hvm"
			elif [ "$VIRT" == "xen-pv" ] ; then
				echo "-property vm_mode=xen"
			fi
		;;
		"")
			if [ "$INSECURE" == "1" ] ; then
				echo "--insecure"
			fi
		;;
	esac
}

function nova_flags() {
	case $1 in
		"")
			if [ "$INSECURE" == "1" ] ; then
				echo "--insecure"
			fi
		;;
	esac
}

function keystone_flags() {
	case $1 in
		"")
			if [ "$INSECURE" == "1" ] ; then
				echo "--insecure"
			fi
		;;
	esac
}

function exit_ok() {
	exit 0
}

function exit_fail() {
	exit 1
}

function exit_error() {
	exit 2
}

function exit_skipped() {
	exit 3
}


if [ "$DEBUG" == "1" ] ; then
	set -x
fi
