#!/bin/bash

source ~/.openrc

source config


function glance_flags() {
	case $1 in
		"image-create")
			if [ "$VIRT" == "kvm" ] ; then
				echo ""
			elif [ "$VIRT" == "xen-hvm" ] ; then
				echo "--property vm_mode=hvm"
			elif [ "$VIRT" == "xen-pv" ] ; then
				echo "-property vm_mode=xen"
			fi
		;;
		*)
			if [ "$INSECURE" == "1" ] ; then
				echo "--insecure"
			fi
		;;
	esac
}




if [ "$DEBUG" == "1" ] ; then
	set -x
fi
