#!/bin/bash

source functions

export OS_TENANT_NAME=admin
export NOVA_PROJECT_ID=$OS_TENANT_NAME

tenantid=$(keystone `keystone_flags` tenant-list | grep openstack | awk '{print $2}')
userid=$(keystone `keystone_flags` user-list | grep ' admin ' | awk '{print $2}')

if [ "$tenantid" != "" ] ; then
	roleid=$(keystone `keystone_flags` user-role-list --user-id $userid --tenant-id $tenantid |grep admin | awk '{print $1}')
	if [ "$roleid" == "" ] ; then
		roleid=$(keystone `keystone_flags` role-list | grep admin | awk '{print $2}')
		if [ "$userid" == "" ] ; then
			keystone `keystone_flags` user-list
			exit_fail
		else
			keystone `keystone_flags` user-get $userid
			keystone `keystone_flags` user-role-add --user-id $userid --role-id $roleid --tenant-id $tenantid
			exit_ok
		fi
	else
		exit_skipped
	fi
else
	exit_skipped
fi
