#!/bin/bash

source functions

imgid=$(glance `glance_flags` image-list --name jeos --status active | grep jeos | awk '{print $2}')

if [ "$imgid" == "" ] ; then
	glance `glance_flags` image-create `glance_flags image-create` \
		--name=jeos --is-public=True --container-format=bare \
		--disk-format=qcow2 --copy-from http://clouddata.cloud.suse.de/images/jeos-64.qcow2
	imgid=$(glance `glance_flags` image-list --name jeos --status active | grep jeos | awk '{print $2}')
	if [ "$imgid" == "" ] ; then
		glance `glance_flags` image-list
		exit 1
	else
		exit 0
	fi
else
	exit 3 # skipped
fi

