#!/bin/bash

source functions

tenantid=$(keystone `keystone_flags` tenant-list | grep openstack | awk '{print $2}')
userid=$(keystone `keystone_flags` user-list | grep test_user | awk '{print $2}')
roleid=$(keystone `keystone_flags` role-list | grep Member | awk '{print $2}')

if [ "$tenantid" != "" ] ; then
	if [ "$userid" == "" ] ; then
		keystone `keystone_flags` user-create --tenant-id $tenantid \
			--name test_user --pass $OS_PASSWORD --email tux@suse.de --enabled true
		userid=$(keystone `keystone_flags` user-list | grep test_user | awk '{print $2}')
		if [ "$userid" == "" ] ; then
			keystone `keystone_flags` user-list
			exit_fail
		else
			keystone `keystone_flags` user-get $userid
			keystone `keystone_flags` user-role-add --user-id $userid --role-id $roleid --tenant-id $tenantid
			exit_ok
		fi
	else
		exit_skipped
	fi
else
	exit_skipped
fi

