#!/bin/bash

source functions

userid=$(keystone `keystone_flags` user-list | grep test_user | awk '{print $2}')

if [ "$userid" != "" ] ; then
	if keystone `keystone_flags` --os-username test_user password-update --new-password openstack123 ; then
		if nova `nova_flags` --os_username test_user --os_password openstack123 list ; then
			keystone `keystone_flags` user-password-update $userid --pass $OS_PASSWORD # reset
			exit_ok
		else
			keystone `keystone_flags` user-password-update $userid --pass $OS_PASSWORD # reset
			exit_fail
		fi
	else
		exit_fail
	fi
else
	exit_skipped
fi
