#!/bin/bash

source functions

imgid=$(glance `glance_flags` image-list --name jeos2 --status active | grep jeos2 | awk '{print $2}')

if [ "$imgid" == "" ] ; then
	glance `glance_flags` image-create `glance_flags image-create` \
		--name=jeos2 --is-public=True --container-format=bare \
		--disk-format=qcow2 --copy-from `glance_flags image-url`
	if glance `glance_flags` image-list --name jeos2 | grep -q jeos2 ; then
		for i in {1..15} ; do
			if glance `glance_flags` image-list --name jeos2 --status active | grep -q jeos2 ; then
				break
			else
				sleep 2
			fi
		done
	fi
	imgid=$(glance `glance_flags` image-list --name jeos2 --status active | grep jeos2 | awk '{print $2}')
	if [ "$imgid" == "" ] ; then
		glance `glance_flags` image-list
		exit_fail
	else
		nova image-show jeos2
		exit_ok
	fi
else
	exit_skipped
fi

