#!/bin/bash

source functions

volid=$(cinder `cinder_flags` list --display-name vol1 --status available | grep vol1 | cut -d " " -f2)
instid=$(nova `nova_flags` list --name jeos_00 | grep jeos_00 | awk '{print $2}')

if [ "$instid" != "" ] && [ "$volid" != "" ] ; then
	cinder `cinder_flags` list | grep $volid | grep $instid && exit_skipped
	nova `nova_flags` volume-attach $instid $volid
	sleep 3
	assoc_entry=$(cinder `cinder_flags` list | grep $volid | grep $instid)
	if [ "$assoc_entry" == "" ] ; then
		cinder `cinder_flags` list
		exit_fail
	else
		exit_ok
	fi
else
	exit_skipped
fi

