#!/bin/bash

source functions

instid=$(nova `nova_flags` list --name jeos_00 | grep jeos_00 | awk '{print $2}')

if [ "$instid" != "" ] ; then
	floating_ip=$(nova `nova_flags` floating-ip-list | grep $instid | awk '{print $2}')
	if [ "$floating_ip" != "" ] ; then
		if ! ssh root@$floating_ip -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 &>/dev/null echo ; then
			nova `nova_flags` floating-ip-list
			exit_fail
		else
			exit_ok
		fi
	else
		exit_skipped
	fi
else
	exit_skipped
fi

