#!/bin/bash

source functions

[ "$VIRT" == "multi" ] || exit_skipped

floating_ip=$(nova `nova_flags` floating-ip-list | grep "^|[^|]*|[ -]*|" | head -1 | awk '{print $2}')
instid=$(nova `nova_flags` list --name jeos_h0 | grep jeos_h0 | awk '{print $2}')

if [ "$instid" != "" ] && [ "$floating_ip" != "" ] ; then
	nova `nova_flags` floating-ip-list | grep $floating_ip | grep $instid && exit_skipped
	nova `nova_flags` add-floating-ip $instid $floating_ip
	assoc_entry=$(nova `nova_flags` floating-ip-list | grep $floating_ip | grep $instid)
	if [ "$assoc_entry" == "" ] ; then
		nova `nova_flags` floating-ip-list
		exit_fail
	else
		exit_ok
	fi
else
	exit_skipped
fi

