#!/bin/bash

source functions

instid=$(nova `nova_flags` list --name jeos_02 | grep jeos_02 | awk '{print $2}')

if [ "$instid" != "" ] ; then
	nova `nova_flags` delete $instid || exit_fail
	for i in {1..30} ; do
		sleep 2
		instid=$(nova `nova_flags` list --name jeos_02 | grep jeos_02 | awk '{print $2}')
		if [ "$instid" == "" ] ; then
			exit_ok
		fi
	done
	echo "instid: '$instid'"
	nova `nova_flags` list --name jeos_02
	exit_fail
else
	exit_skipped
fi
