#!/bin/bash

source functions

[ "$VIRT" == "multi" ] || exit_skipped

instid=$(nova `nova_flags` list --name jeos_h0 | grep jeos_h0 | awk '{print $2}')

if [ "$instid" != "" ] ; then
	floating_ip=$(nova `nova_flags` floating-ip-list | grep $instid | awk '{print $2}')
	if [ "$floating_ip" != "" ] ; then
		nova `nova_flags` remove-floating-ip $instid $floating_ip
		floating_ip=$(nova `nova_flags` floating-ip-list | grep $floating_ip | grep "^|[^|]*|[ -]*|" | awk '{print $2}')
		if [ "$floating_ip" == "" ] ; then
			nova `nova_flags` floating-ip-list
			exit_fail
		else
			exit_ok
		fi
	else
		exit_skipped
	fi
else
	exit_skipped
fi

