#!/bin/bash

source functions

[ "$VIRT" == "multi" ] || exit_skipped

instid=$(nova `nova_flags` list --name jeos_p0 | grep jeos_p0 | awk '{print $2}')

if [ "$instid" != "" ] ; then
	nova `nova_flags` delete $instid || exit_fail
	for i in {1..30} ; do
		sleep 2
		instid=$(nova `nova_flags` list --name jeos_p0 | grep jeos_p0 | awk '{print $2}')
		if [ "$instid" == "" ] ; then
			exit_ok
		fi
	done
	echo "instid: '$instid'"
	nova `nova_flags` list --name jeos_p0
	exit_fail
else
	exit_skipped
fi
