#!/bin/bash

source functions

glance `glance_flags` image-show jeos1 || exit_skipped
nova `nova_flags` flavor-show m1.small || exit_skipped


imgid=$(glance `glance_flags` image-list --name jeos1 --status active | grep jeos1 | awk '{print $2}')
flavorid=$(nova `nova_flags` flavor-list | grep "m1.small" | awk '{print $2}')

instid=$(nova `nova_flags` --os_tenant_name admin list --name jeos_03 | grep jeos_03 | awk '{print $2}')

if [ "$instid" == "" ] ; then
	nova `nova_flags` --os_tenant_name admin boot --flavor $flavorid --image $imgid jeos_03 || exit_fail
	for i in {1..30} ; do
		sleep 2
		instid=$(nova `nova_flags` --os_tenant_name admin list --name jeos_03 --status ACTIVE | grep jeos_03 | awk '{print $2}')
		if [ "$instid" != "" ] ; then
			nova --os_tenant_name admin `nova_flags` list
			exit_ok
		fi
	done
	exit_fail
else
	echo "Instance already running: '$instid'"
	exit_skipped
fi

