#!/bin/bash

source functions

instid=$(nova `nova_flags` --os_tenant_name admin list --name jeos_03 | grep jeos_03 | awk '{print $2}')

if [ "$instid" != "" ] ; then
	nova `nova_flags` --os_tenant_name admin delete $instid || exit_fail
	for i in {1..30} ; do
		sleep 2
		instid=$(nova `nova_flags` --os_tenant_name admin list --name jeos_03 | grep jeos_03 | awk '{print $2}')
		if [ "$instid" == "" ] ; then
			exit_ok
		fi
	done
	echo "instid: '$instid'"
	nova `nova_flags` --os_tenant_name admin list --name jeos_03
	exit_fail
else
	exit_skipped
fi
