#!/bin/bash

source functions

glance `glance_flags` image-show jeos1 || exit_skipped
nova `nova_flags` flavor-show m1.tiny || exit_skipped

imgid=$(glance `glance_flags` image-list --name jeos1 --status active | grep jeos1 | awk '{print $2}')
flavorid=$(nova `nova_flags` flavor-list | grep "m1.tiny" | awk '{print $2}')

instid=$(nova `nova_flags` list --name jeos_cycle | grep jeos_cycle | awk '{print $2}')

if [ "$instid" == "" ] ; then
	for i in `seq 1 $CYCLE_COUNT` ; do
		echo "CYCLE #$i ..."
		nova `nova_flags` --os_username crowbar boot --flavor $flavorid --image $imgid jeos_cycle --poll || exit_fail
		instid=$(nova `nova_flags` --os_username crowbar list --name jeos_cycle | grep jeos_cycle | awk '{print $2}')
		nova `nova_flags` --os_username crowbar delete $instid || exit_fail
		for i in {1..30} ; do
			sleep 2
			instid=$(nova `nova_flags` --os_username crowbar list --name jeos_cycle | grep jeos_cycle | awk '{print $2}')
			if [ "$instid" == "" ] ; then
				continue 2
			fi
		done
		echo "FAILED IN CYCLE #$i!"
		nova `nova_flags` --os_username crowbar list --name jeos_cycle
		exit_fail
	done
	exit_ok
else
	echo "Instance already running: '$instid'"
	exit_skipped
fi

