#!/bin/bash

source functions

glance `glance_flags` image-show jeos1 || exit_skipped
glance `glance_flags` image-show jeos2 || exit_skipped
nova `nova_flags` flavor-show m1.small || exit_skipped

function get_imgid() {
	echo $(glance `glance_flags` image-list --name $1 --status active | grep $1 | awk '{print $2}')
}

flavorid=$(nova `nova_flags` flavor-list | grep "m1.small" | awk '{print $2}')

instid=$(nova `nova_flags` list --name jeos_multiimg | grep jeos_multiimg | awk '{print $2}')

if [ "$instid" == "" ] ; then
	for i in jeos1 jeos2 ; do
		nova `nova_flags` --os_username crowbar boot --flavor $flavorid --image `get_imgid $i` jeos_multiimg_$i --poll &
		pids="$pids $!"
	done
	for pid in $pids ; do
		wait $pid || exit_fail
	done
	echo "Done Building"
	instids=$(nova `nova_flags` --os_username crowbar list --name jeos_multiimg --status ACTIVE | grep jeos_multiimg | awk '{print $2}')
	instidcount=0
	for instid in $instids ; do
		let instidcount=instidcount+1
		nova `nova_flags` --os_username crowbar delete $instid || exit_fail
	done
	echo "Done Deleting"
	for i in {1..30} ; do
		sleep 2
		instid=$(nova `nova_flags` --os_username crowbar list --name jeos_multiimg | grep jeos_multiimg | awk '{print $2}')
		if [ "$instid" == "" ] ; then
			exit_ok
		fi
	done
	nova `nova_flags` --os_username crowbar list --name jeos_multiimg
	exit_fail
else
	echo "Instance already running: '$instid'"
	exit_skipped
fi

