#!/bin/bash

source functions

if keystone `keystone_flags` service-list | grep -q ceilometer ; then
	if ceilometer `ceilometer_flags` meter-list ; then
		exit_ok
	else
		exit_fail
	fi
else
	exit_skipped
fi

