#!/bin/bash

source functions

if keystone `keystone_flags` service-list | grep -q heat ; then
	heat `heat_flags` stack-list | grep -q jeos_00 || exit_skipped
	if heat `heat_flags` stack-delete jeos_00 ; then
		exit_ok
	else
		exit_fail
	fi
else
	exit_skipped
fi

