#!/bin/bash

source functions

imgid=$(glance `glance_flags` image-list --name jeos --status active | grep jeos | awk '{print $2}')

if [ "$imgid" != "" ] ; then
	glance `glance_flags` image-delete $imgid
	imgid=$(glance `glance_flags` image-list --name jeos --status active | grep jeos | awk '{print $2}')
	if [ "$imgid" != "" ] ; then
		echo "imgid: '$imgid'"
		glance `glance_flags` image-list --name jeos --status active
		exit 1
	else
		exit 0
	fi
else
	exit 3 # skipped
fi
