#!/bin/bash

source functions

imgid=$(glance `glance_flags` image-list --name jeos --status active | grep jeos | awk '{print $2}')

if [ "$imgid" != "" ] ; then
	glance `glance_flags` image-delete $imgid
	imgid=$(glance `glance_flags` image-list --name jeos --status active | grep jeos | awk '{print $2}')
	if [ "$imgid" != "" ] ; then
		echo "imgid: '$imgid'"
		glance `glance_flags` image-list --name jeos --status active
		exit_fail
	else
		exit_ok
	fi
else
	exit_skipped
fi
